// <auto-generated />
using System;
using Beosztasmester.Model;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Beosztasmester.Migrations
{
    [DbContext(typeof(DataContext))]
    partial class DataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Beosztasmester.Models.Data.Assignment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Date")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Employee_Id")
                        .HasColumnType("integer");

                    b.Property<bool>("IsLocked")
                        .HasColumnType("boolean");

                    b.Property<int?>("Roster_VersionId")
                        .HasColumnType("integer");

                    b.Property<int>("Shift_Type_Id")
                        .HasColumnType("integer");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Version_Id")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("Employee_Id");

                    b.HasIndex("Roster_VersionId");

                    b.HasIndex("Shift_Type_Id");

                    b.ToTable("Assignments");
                });

            modelBuilder.Entity("Beosztasmester.Models.Data.Audit_Entry", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ChangesJson")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<string>("Entity")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Entity_Id")
                        .HasColumnType("integer");

                    b.Property<string>("Operation")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("User_Id")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Audit_Entries");
                });

            modelBuilder.Entity("Beosztasmester.Models.Data.Competency", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.ToTable("Competencies");
                });

            modelBuilder.Entity("Beosztasmester.Models.Data.Demand", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("Competency_Id")
                        .HasColumnType("integer");

                    b.Property<DateTime>("Date")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("Max_Headcount")
                        .HasColumnType("integer");

                    b.Property<int>("Min_Headcount")
                        .HasColumnType("integer");

                    b.Property<int>("Organizational_Unit_Id")
                        .HasColumnType("integer");

                    b.Property<int>("Shift_Type_Id")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("Competency_Id");

                    b.HasIndex("Organizational_Unit_Id");

                    b.HasIndex("Shift_Type_Id");

                    b.ToTable("Demands");
                });

            modelBuilder.Entity("Beosztasmester.Models.Data.Demand_Template", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("Competency_Id")
                        .HasColumnType("integer");

                    b.Property<int>("DayOfWeek")
                        .HasColumnType("integer");

                    b.Property<int?>("Max_Headcount")
                        .HasColumnType("integer");

                    b.Property<int>("Min_Headcount")
                        .HasColumnType("integer");

                    b.Property<int>("Organizational_Unit_Id")
                        .HasColumnType("integer");

                    b.Property<int>("Shift_Type_Id")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("Competency_Id");

                    b.HasIndex("Organizational_Unit_Id");

                    b.HasIndex("Shift_Type_Id");

                    b.ToTable("Demand_Templates");
                });

            modelBuilder.Entity("Beosztasmester.Models.Data.Employee", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Contract_Hours_Per_Week")
                        .HasColumnType("integer");

                    b.Property<DateTime>("Entry_Date")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("Exit_Date")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int>("Organizational_Unit_Id")
                        .HasColumnType("integer");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.HasIndex("Organizational_Unit_Id");

                    b.ToTable("Employees");
                });

            modelBuilder.Entity("Beosztasmester.Models.Data.Employee_Competency", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Competency_Id")
                        .HasColumnType("integer");

                    b.Property<int>("Employee_Id")
                        .HasColumnType("integer");

                    b.Property<DateTime>("Valid_From")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("Valid_To")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Competency_Id");

                    b.HasIndex("Employee_Id");

                    b.ToTable("Employee_Competencies");
                });

            modelBuilder.Entity("Beosztasmester.Models.Data.Horizon", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Organizational_Unit_Id")
                        .HasColumnType("integer");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Organizational_Unit_Id");

                    b.ToTable("Horizons");
                });

            modelBuilder.Entity("Beosztasmester.Models.Data.Organizational_Unit", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int?>("Parent_Id")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("Parent_Id");

                    b.ToTable("Organizational_Units");
                });

            modelBuilder.Entity("Beosztasmester.Models.Data.Request", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Date")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Employee_Id")
                        .HasColumnType("integer");

                    b.Property<int>("Priority")
                        .HasColumnType("integer");

                    b.Property<int?>("Shift_Type_Id")
                        .HasColumnType("integer");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.HasIndex("Employee_Id");

                    b.HasIndex("Shift_Type_Id");

                    b.ToTable("Requests");
                });

            modelBuilder.Entity("Beosztasmester.Models.Data.Roster_Version", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Created_By")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("Created_Date")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Horizon_Id")
                        .HasColumnType("integer");

                    b.Property<double?>("Objective_Value")
                        .HasColumnType("double precision");

                    b.Property<string>("Solution_Metadata_Json")
                        .HasColumnType("jsonb");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Version_Number")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("Horizon_Id");

                    b.ToTable("Roster_Versions");
                });

            modelBuilder.Entity("Beosztasmester.Models.Data.Rule", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Is_Active")
                        .HasColumnType("boolean");

                    b.Property<bool>("Is_Hard")
                        .HasColumnType("boolean");

                    b.Property<int>("Organizational_Unit_Id")
                        .HasColumnType("integer");

                    b.Property<string>("Parameters_Json")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<string>("Scope")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Scope_Ref")
                        .HasColumnType("text");

                    b.Property<string>("Type_Code")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Weight")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("Organizational_Unit_Id");

                    b.ToTable("Rules");
                });

            modelBuilder.Entity("Beosztasmester.Models.Data.Shift_Type", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<int>("Duration_Minutes")
                        .HasColumnType("integer");

                    b.Property<TimeSpan>("End_Time")
                        .HasColumnType("interval");

                    b.Property<bool>("Is_Night_Shift")
                        .HasColumnType("boolean");

                    b.Property<int>("Organizational_Unit_Id")
                        .HasColumnType("integer");

                    b.Property<TimeSpan>("Start_Time")
                        .HasColumnType("interval");

                    b.HasKey("Id");

                    b.HasIndex("Organizational_Unit_Id");

                    b.ToTable("Shift_Types");
                });

            modelBuilder.Entity("Beosztasmester.Models.Data.Unavailability", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Employee_Id")
                        .HasColumnType("integer");

                    b.Property<DateTime>("End_Date")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Reason")
                        .HasColumnType("text");

                    b.Property<DateTime>("Start_Date")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.HasIndex("Employee_Id");

                    b.ToTable("Unavailabilities");
                });

            modelBuilder.Entity("Beosztasmester.Models.Data.Assignment", b =>
                {
                    b.HasOne("Beosztasmester.Models.Data.Employee", "Employee")
                        .WithMany("Assignments")
                        .HasForeignKey("Employee_Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Beosztasmester.Models.Data.Roster_Version", null)
                        .WithMany("Assignments")
                        .HasForeignKey("Roster_VersionId");

                    b.HasOne("Beosztasmester.Models.Data.Shift_Type", "Shift_Type")
                        .WithMany()
                        .HasForeignKey("Shift_Type_Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Employee");

                    b.Navigation("Shift_Type");
                });

            modelBuilder.Entity("Beosztasmester.Models.Data.Demand", b =>
                {
                    b.HasOne("Beosztasmester.Models.Data.Competency", "Competency")
                        .WithMany()
                        .HasForeignKey("Competency_Id");

                    b.HasOne("Beosztasmester.Models.Data.Organizational_Unit", "Organizational_Unit")
                        .WithMany()
                        .HasForeignKey("Organizational_Unit_Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Beosztasmester.Models.Data.Shift_Type", "ShiftType")
                        .WithMany()
                        .HasForeignKey("Shift_Type_Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Competency");

                    b.Navigation("Organizational_Unit");

                    b.Navigation("ShiftType");
                });

            modelBuilder.Entity("Beosztasmester.Models.Data.Demand_Template", b =>
                {
                    b.HasOne("Beosztasmester.Models.Data.Competency", "Competency")
                        .WithMany()
                        .HasForeignKey("Competency_Id");

                    b.HasOne("Beosztasmester.Models.Data.Organizational_Unit", "Organizational_Unit")
                        .WithMany()
                        .HasForeignKey("Organizational_Unit_Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Beosztasmester.Models.Data.Shift_Type", "Shift_Type")
                        .WithMany()
                        .HasForeignKey("Shift_Type_Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Competency");

                    b.Navigation("Organizational_Unit");

                    b.Navigation("Shift_Type");
                });

            modelBuilder.Entity("Beosztasmester.Models.Data.Employee", b =>
                {
                    b.HasOne("Beosztasmester.Models.Data.Organizational_Unit", "Organizational_Unit")
                        .WithMany("Employees")
                        .HasForeignKey("Organizational_Unit_Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Organizational_Unit");
                });

            modelBuilder.Entity("Beosztasmester.Models.Data.Employee_Competency", b =>
                {
                    b.HasOne("Beosztasmester.Models.Data.Competency", "Competency")
                        .WithMany("Employee_Competencies")
                        .HasForeignKey("Competency_Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Beosztasmester.Models.Data.Employee", "Employee")
                        .WithMany("Employee_Competencies")
                        .HasForeignKey("Employee_Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Competency");

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("Beosztasmester.Models.Data.Horizon", b =>
                {
                    b.HasOne("Beosztasmester.Models.Data.Organizational_Unit", "Organizational_Unit")
                        .WithMany()
                        .HasForeignKey("Organizational_Unit_Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Organizational_Unit");
                });

            modelBuilder.Entity("Beosztasmester.Models.Data.Organizational_Unit", b =>
                {
                    b.HasOne("Beosztasmester.Models.Data.Organizational_Unit", "Parent_Unit")
                        .WithMany("Child_Units")
                        .HasForeignKey("Parent_Id");

                    b.Navigation("Parent_Unit");
                });

            modelBuilder.Entity("Beosztasmester.Models.Data.Request", b =>
                {
                    b.HasOne("Beosztasmester.Models.Data.Employee", "Employee")
                        .WithMany("Requests")
                        .HasForeignKey("Employee_Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Beosztasmester.Models.Data.Shift_Type", "Shift_Type")
                        .WithMany()
                        .HasForeignKey("Shift_Type_Id");

                    b.Navigation("Employee");

                    b.Navigation("Shift_Type");
                });

            modelBuilder.Entity("Beosztasmester.Models.Data.Roster_Version", b =>
                {
                    b.HasOne("Beosztasmester.Models.Data.Horizon", "Horizon")
                        .WithMany("Roster_Versions")
                        .HasForeignKey("Horizon_Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Horizon");
                });

            modelBuilder.Entity("Beosztasmester.Models.Data.Rule", b =>
                {
                    b.HasOne("Beosztasmester.Models.Data.Organizational_Unit", "Organizational_Unit")
                        .WithMany()
                        .HasForeignKey("Organizational_Unit_Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Organizational_Unit");
                });

            modelBuilder.Entity("Beosztasmester.Models.Data.Shift_Type", b =>
                {
                    b.HasOne("Beosztasmester.Models.Data.Organizational_Unit", "Organizational_Unit")
                        .WithMany()
                        .HasForeignKey("Organizational_Unit_Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Organizational_Unit");
                });

            modelBuilder.Entity("Beosztasmester.Models.Data.Unavailability", b =>
                {
                    b.HasOne("Beosztasmester.Models.Data.Employee", "Employee")
                        .WithMany("Unavailabilities")
                        .HasForeignKey("Employee_Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("Beosztasmester.Models.Data.Competency", b =>
                {
                    b.Navigation("Employee_Competencies");
                });

            modelBuilder.Entity("Beosztasmester.Models.Data.Employee", b =>
                {
                    b.Navigation("Assignments");

                    b.Navigation("Employee_Competencies");

                    b.Navigation("Requests");

                    b.Navigation("Unavailabilities");
                });

            modelBuilder.Entity("Beosztasmester.Models.Data.Horizon", b =>
                {
                    b.Navigation("Roster_Versions");
                });

            modelBuilder.Entity("Beosztasmester.Models.Data.Organizational_Unit", b =>
                {
                    b.Navigation("Child_Units");

                    b.Navigation("Employees");
                });

            modelBuilder.Entity("Beosztasmester.Models.Data.Roster_Version", b =>
                {
                    b.Navigation("Assignments");
                });
#pragma warning restore 612, 618
        }
    }
}
